#!/usr/bin/env python3
"""Write theme/theme.css and tex/tikz-tensors-colors.tex from theme/tokens.toml.

    python3 scripts/theme.py            # regenerate both
    python3 scripts/theme.py --check    # fail if either is out of date (CI)

Standard library only (tomllib, Python 3.11+), so it runs anywhere without an
environment. The CSS carries every token as a custom property, light on :root,
dark under prefers-color-scheme and [data-theme="dark"], so a page switches by
tokens alone; the TeX file defines one xcolor per token as tt<name>, plus the
physics colours under their short names (ele, nuc, ...) that diagrams use.

A value is either a literal "#rrggbb" or a reference to a step of [ramp],
optionally mixed: "blue2", "blue3 +35% black", "green +90% white". Resolving
them here is what lets a colour code be written once: the scales hold the
codes, and everything else is an assignment onto them, so moving a scale moves
every figure and every page that named it.
"""
import pathlib
import re
import sys
import tomllib

ROOT = pathlib.Path(__file__).resolve().parents[1]
RAW = tomllib.loads((ROOT / "theme/tokens.toml").read_text())
HEAD = "generated by scripts/theme.py from theme/tokens.toml -- edit that file, not this one"
MIX = re.compile(r"^(\w+)(?:\s*\+\s*(\d+)%\s*(white|black))?$")


def resolve(value: str, ramp: dict) -> str:
    """A literal, or a step of the ramp, optionally mixed toward white or black."""
    if value.startswith("#"):
        return value
    m = MIX.match(value.strip())
    if not m or m.group(1) not in ramp:
        sys.exit(f"theme/tokens.toml: {value!r} is neither a #rrggbb nor a step of "
                 f"[ramp] ({', '.join(sorted(ramp))}), optionally '+NN% white|black'")
    step, pct, towards = m.group(1), m.group(2), m.group(3)
    rgb = [int(ramp[step][i:i + 2], 16) for i in (1, 3, 5)]
    if pct:
        t, end = int(pct) / 100, 255 if towards == "white" else 0
        rgb = [round(c + (end - c) * t) for c in rgb]
    return "#%02x%02x%02x" % tuple(rgb)


RAMP = RAW.get("ramp", {})
T = {name: {k: resolve(v, RAMP) for k, v in section.items()}
     for name, section in RAW.items()}


def css() -> str:
    def block(d):
        return "".join(f"--{k}:{v};" for k, v in d.items())
    phys = "".join(block(T[k]) for k in T if k not in ("light", "dark"))
    return (f"/* {HEAD} */\n"
            f":root{{{block(T['light'])}{phys}color-scheme:light}}\n"
            f"@media (prefers-color-scheme:dark){{:root:not([data-theme=\"light\"]){{{block(T['dark'])}color-scheme:dark}}}}\n"
            f":root[data-theme=\"dark\"]{{{block(T['dark'])}color-scheme:dark}}\n")


def tex() -> str:
    def name(k):
        return "tt" + k.replace("-", "")
    lines = [f"% {HEAD}"]
    lines += [f"\\definecolor{{{name(k)}}}{{HTML}}{{{v[1:].upper()}}}" for k, v in T["light"].items()]
    for section in (k for k in T if k not in ("light", "dark")):
        lines += [f"\\definecolor{{{k}}}{{HTML}}{{{v[1:].upper()}}}"
                  for k, v in T[section].items()]
    return "\n".join(lines) + "\n"


def palette() -> str:
    """The chart's data: every step of the ramp and what actually names it.

    Read out of the table rather than written beside it, so the chart cannot
    claim a role the theme does not assign, or miss one it does.
    """
    order = list(RAMP)
    scales: dict[str, list[str]] = {}
    for step in order:
        scales.setdefault(step.rstrip("0123456789") or step, []).append(step)
    figure: dict[str, list[str]] = {s: [] for s in order}
    page: dict[str, dict[str, list[str]]] = {s: {"light": [], "dark": []} for s in order}
    for section, body in RAW.items():
        if section == "ramp":
            continue
        for key, value in body.items():
            if value.startswith("#"):
                continue
            step = value.split()[0]
            if section in ("light", "dark"):
                page[step][section].append(key)
            else:
                figure[step].append(key)

    rows = []
    for r, (_, steps) in enumerate(scales.items()):
        for c, step in enumerate(steps):
            light, dark = page[step]["light"], page[step]["dark"]
            lines = ([f"light {', '.join(light)}"] if light else []) + \
                    ([f"dark {', '.join(dark)}"] if dark else [])
            fig = ", ".join(figure[step])
            pag = "\\\\".join(lines)          # a TeX line break between the two modes
            rows.append(f"    {step}/{RAMP[step][1:].upper()}/{{{fig}}}/{{{pag}}}/{c * 6}/{r}")
    bars = []
    for r, (name, steps) in enumerate(scales.items()):
        ends = (steps + steps[-1:] * 2)[:3]   # a one-step scale is a flat bar
        bars.append(f"    {'/'.join(ends)}/{name}/{r}")
    used = [s for s in order if figure[s] or page[s]["light"] or page[s]["dark"]]
    spare = [s for s in order if s not in used]
    count = (f"{len(order)} steps defined, {len(used)} of them named by something. "
             + (f"{', '.join(spare)} {'is' if len(spare) == 1 else 'are'} defined and unused."
                if spare else "Every step is used."))
    return (f"% {HEAD}\n"
            f"% The palette chart's data. examples/00-palette.tex draws this and nothing\n"
            f"% else, so what it says about a step is what theme/tokens.toml assigns.\n"
            f"\\def\\tnpalette{{%\n" + ",\n".join(rows) + "%\n}\n"
            f"\\def\\tnpalettescales{{%\n" + ",\n".join(bars) + "%\n}\n"
            f"\\def\\tnpalettecount{{{count}}}\n")


OUT = {ROOT / "theme/theme.css": css(),
       ROOT / "tex/tikz-tensors-colors.tex": tex(),
       ROOT / "tex/tikz-tensors-palette.tex": palette()}

if __name__ == "__main__":
    stale = [p for p, s in OUT.items() if not p.exists() or p.read_text() != s]
    if "--check" in sys.argv:
        for p in stale:
            print(f"out of date: {p.relative_to(ROOT)} (run scripts/theme.py)", file=sys.stderr)
        sys.exit(1 if stale else 0)
    for p, s in OUT.items():
        p.write_text(s)
        print(p.relative_to(ROOT))
