#!/usr/bin/env python3
"""Write theme/theme.css and tex/tikz-tensors-colors.tex from theme/tokens.toml.

    python3 scripts/theme.py            # regenerate both
    python3 scripts/theme.py --check    # fail if either is out of date (CI)

Standard library only (tomllib, Python 3.11+), so it runs anywhere without an
environment. The CSS carries every token as a custom property, light on :root,
dark under prefers-color-scheme and [data-theme="dark"], so a page switches by
tokens alone; the TeX file defines one xcolor per token as tt<name>, plus the
physics colours under their short names (ele, nuc, ...) that diagrams use.
"""
import pathlib
import sys
import tomllib

ROOT = pathlib.Path(__file__).resolve().parents[1]
T = tomllib.loads((ROOT / "theme/tokens.toml").read_text())
HEAD = "generated by scripts/theme.py from theme/tokens.toml -- edit that file, not this one"


def css() -> str:
    def block(d):
        return "".join(f"--{k}:{v};" for k, v in d.items())
    phys = block(T["physics"])
    return (f"/* {HEAD} */\n"
            f":root{{{block(T['light'])}{phys}color-scheme:light}}\n"
            f"@media (prefers-color-scheme:dark){{:root:not([data-theme=\"light\"]){{{block(T['dark'])}color-scheme:dark}}}}\n"
            f":root[data-theme=\"dark\"]{{{block(T['dark'])}color-scheme:dark}}\n")


def tex() -> str:
    def name(k):
        return "tt" + k.replace("-", "")
    lines = [f"% {HEAD}"]
    lines += [f"\\definecolor{{{name(k)}}}{{HTML}}{{{v[1:].upper()}}}" for k, v in T["light"].items()]
    lines += [f"\\definecolor{{{k}}}{{HTML}}{{{v[1:].upper()}}}" for k, v in T["physics"].items()]
    return "\n".join(lines) + "\n"


OUT = {ROOT / "theme/theme.css": css(), ROOT / "tex/tikz-tensors-colors.tex": tex()}

if __name__ == "__main__":
    stale = [p for p, s in OUT.items() if not p.exists() or p.read_text() != s]
    if "--check" in sys.argv:
        for p in stale:
            print(f"out of date: {p.relative_to(ROOT)} (run scripts/theme.py)", file=sys.stderr)
        sys.exit(1 if stale else 0)
    for p, s in OUT.items():
        p.write_text(s)
        print(p.relative_to(ROOT))
